### ISSUE TITLE
setting symarray as parameter

### ISSUE THREAD

**Issue by Ziaeemehr** [neurophysik/jitcsde#3]
Hello,
Is it also possible to pass a `symengin.symarray` as parameter to the function?

```python
import numpy as np
import pylab as plt
from jitcsde import y, jitcsde
from symengine import Symbol, symarray


np.random.seed(2)


def Epileptor2D():
    for i in range(N):
        yield 1.0 - y(0)*y(0)*y(0) - 2.0*y(0)*y(0) - y(1) + I
        yield inv_tau * (4 * (y(0) - eta[i]) - y(1))


# PARAMETERS
N = 2
I = 3.1
tau = 10
sigma = 0.1
inv_tau = 0.1
eta0 = [-3.5, -1.5]
eta = symarray("eta", 2)

dt = 0.1
T = 100.0
g = [sigma, sigma] * 2

initial_state = np.array([-2.5, 3.5, -2.1, 3.0])


ts = np.arange(0, T, dt)
nt = len(ts)

SDE = jitcsde(Epileptor2D, g, control_pars=eta)
SDE.set_initial_value(initial_state, 0.0)
SDE.set_parameters(eta0)

# data = np.zeros((nt, 4))
# for i in range(nt):
#     data[i, :] = SDE.integrate(ts[i])

# fig, ax = plt.subplots(1, figsize=(10, 4.5))
# ax.plot(ts, data[:, 0], lw=0.5, color='k')
# ax.plot(ts, data[:, 2], lw=0.5, color='r')
# ax.set_xlabel("time [ms]")
# ax.set_ylabel("x")
# plt.savefig("fig.png", dpi=150)
# plt.show()
```

Ii does not give any error but it seems that `eta` is not assigned as expected.  I give 2 different value but from the figure output it seems that both values are assigned by the the first element.  eta larger than -1.6 produce regular oscillations.

eta0 = [-3.5, -1.5]
![Selection_001](https://user-images.githubusercontent.com/7780103/126876075-43543536-3497-4234-b841-a95f2fa6a789.jpg)

eta0 = [-1.5, -3.5]
![Selection_002](https://user-images.githubusercontent.com/7780103/126876079-00875b15-e94e-4230-890f-b5383acd0da3.jpg)

Thank you in advance.

**Comment by Wrzlprmft** [comment]
You can use a `symarray` simply because its an iterable of normal symbols and JiTCSDE never sees anything other than its elements. However, I don’t think your differential equations (`Epileptor2D`) are what you intend and instead you want to use:

``` Python 3
def Epileptor2D():
    for i in range(N):
        yield 1.0 - y(2*i)**3 - 2.0*y(2*i)**2 - y(2*i+1) + I
        yield inv_tau * (4 * (y(2*i) - eta[i]) - y(2*i+1))
```

Some side notes on your code:

* Use your variable for the number of oscillators (`N`) wherever you can, e.g., write `eta = symarray("eta", N)`.
* There is no point to use multiplications for small powers. It’s all the same to SymEngine, and the compiler will take care of it with normal optimisation settings. Instead it’s a potential source of human errors.
* `np.random.seed` has no effect on JiTCSDE. You need to use `SDE.set_seed` if you want to fix JiTCSDE’s random numbers.

**Comment by Ziaeemehr** [comment]
Great, thanks for the complete answer.
